//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComebacksSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProblemResponsibleCategory
    {
        public ProblemResponsibleCategory()
        {
            this.ComebackReasons = new HashSet<ComebackReason>();
        }
    
        public int ProblemResponsibilityCategory_ID { get; set; }
        public string ProblemResponsibilityCategory_Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<ComebackReason> ComebackReasons { get; set; }
    }
}
