//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComebacksSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_SubReasons
    {
        public int Comeback_SubReason_ID { get; set; }
        public string SubReasonDescription { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> ComebackReason_ID { get; set; }
        public string ReasonDescription { get; set; }
    }
}
